# Generated by Django 2.0.3 on 2019-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_category_id', models.IntegerField(verbose_name='支払いカテゴリID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('memo', models.CharField(max_length=100, verbose_name='備考')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('payment_unit_id', models.IntegerField(verbose_name='支払い単位ID')),
                ('payment_limit', models.IntegerField(verbose_name='支払いリミット')),
                ('family_id', models.IntegerField(verbose_name='家族ID')),
                ('member_id', models.IntegerField(verbose_name='メンバーID')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('sample', models.CharField(max_length=100, verbose_name='例')),
                ('memo', models.CharField(max_length=100, verbose_name='備考')),
                ('family_id', models.IntegerField(verbose_name='家族ID')),
                ('member_id', models.IntegerField(verbose_name='メンバーID')),
            ],
            options={
                'db_table': 'payment_category',
            },
        ),
        #追記 動作未確認
        migrations.RunSQL("""INSERT INTO `hm`.`payment_category` (`id`, `name`, `sample`, `memo`, `family_id`, `member_id`) VALUES ('1', '生活費', '家賃、水道代、携帯', '固定額減っていくもので、切り詰められないもの', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`payment_category` (`id`, `name`, `sample`, `memo`, `family_id`, `member_id`) VALUES ('2', '食費', '朝食、昼食、夕食', '基本的な朝夕の食費。無駄遣いを見れる。', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`payment_category` (`id`, `name`, `sample`, `memo`, `family_id`, `member_id`) VALUES ('3', '飲食費', '飲み会', '飲み会の頻度をコントロールするため。', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`payment_category` (`id`, `name`, `memo`, `family_id`, `member_id`) VALUES ('4', '遊興費', 'ここはあまり管理しない', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`payment_category` (`id`, `name`, `sample`, `family_id`, `member_id`) VALUES ('5', 'チャージ', 'チャージ', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`payment_category` (`id`, `name`, `sample`, `memo`, `family_id`, `member_id`) VALUES ('6', '収入', '給料、資産引き出し', '長期的な年収の推移を管理したい', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`payment_category` (`id`, `name`, `memo`, `family_id`, `member_id`) VALUES ('7', 'secret', '画面から消すモードを検討中', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`payment_category` (`id`, `name`, `memo`, `family_id`, `member_id`) VALUES ('8', 'その他', 'その他として、一旦つけて置けるように', '1', '1');"""),
        # 動作未確認ここまで
        migrations.CreateModel(
            name='PaymentUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
            ],
            options={
                'db_table': 'payment_unit',
            },
        ),
        #追記　動作未確認
        migrations.RunSQL("""INSERT INTO `payment_unit` (`id`,`name`) VALUES (1,'回');"""),
        migrations.RunSQL("""INSERT INTO `payment_unit` (`id`,`name`) VALUES (2,'年');"""),
        migrations.RunSQL("""INSERT INTO `payment_unit` (`id`,`name`) VALUES (3,'月');"""),
        migrations.RunSQL("""INSERT INTO `payment_unit` (`id`,`name`) VALUES (4,'週');"""),
        migrations.RunSQL("""INSERT INTO `payment_unit` (`id`,`name`) VALUES (5,'日');"""),
        #追記終了
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('wallet_type_id', models.IntegerField(verbose_name='財布種別ID')),
                ('balance', models.IntegerField(verbose_name='残高')),
                ('family_id', models.IntegerField(verbose_name='家族ID')),
                ('member_id', models.IntegerField(verbose_name='メンバーID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('del_flg', models.BooleanField(verbose_name='削除フラグ')),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('family_id', models.IntegerField(verbose_name='家族ID')),
                ('member_id', models.IntegerField(verbose_name='メンバーID')),
            ],
            options={
                'db_table': 'wallet_type',
            },
        ),
        # 追記　動作未確認
        migrations.RunSQL("""INSERT INTO `hm`.`wallet_type` (`id`, `name`, `family_id`, `member_id`) VALUES ('1', '現金', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`wallet_type` (`id`, `name`, `family_id`, `member_id`) VALUES ('2', '銀行', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`wallet_type` (`id`, `name`, `family_id`, `member_id`) VALUES ('3', 'デビットカード', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`wallet_type` (`id`, `name`, `family_id`, `member_id`) VALUES ('4', '後払い', '1', '1');"""),
        migrations.RunSQL("""INSERT INTO `hm`.`wallet_type` (`id`, `name`, `family_id`, `member_id`) VALUES ('5', '円以外', '1', '1');"""),
        # 追記終了
    ]
