# Generated by Django 2.0.3 on 2019-04-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='family_id',
            field=models.IntegerField(null=True, verbose_name='家族ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member_id',
            field=models.IntegerField(null=True, verbose_name='メンバーID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='memo',
            field=models.CharField(max_length=100, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_limit',
            field=models.IntegerField(null=True, verbose_name='支払いリミット'),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='family_id',
            field=models.IntegerField(null=True, verbose_name='家族ID'),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='member_id',
            field=models.IntegerField(null=True, verbose_name='メンバーID'),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='memo',
            field=models.CharField(max_length=100, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='sample',
            field=models.CharField(max_length=100, null=True, verbose_name='例'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='del_flg',
            field=models.BooleanField(default=0, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='family_id',
            field=models.IntegerField(null=True, verbose_name='家族ID'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='member_id',
            field=models.IntegerField(null=True, verbose_name='メンバーID'),
        ),
        migrations.AlterField(
            model_name='wallettype',
            name='family_id',
            field=models.IntegerField(null=True, verbose_name='家族ID'),
        ),
        migrations.AlterField(
            model_name='wallettype',
            name='member_id',
            field=models.IntegerField(null=True, verbose_name='メンバーID'),
        ),
    ]
