# Generated by Django 2.0.3 on 2019-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='金額'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='family_id',
            field=models.IntegerField(null=True, verbose_name='家族ID'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='member_id',
            field=models.IntegerField(null=True, verbose_name='メンバーID'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='memo',
            field=models.CharField(max_length=100, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='payment_category_id',
            field=models.IntegerField(null=True, verbose_name='支払いカテゴリID'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='payment_limit',
            field=models.IntegerField(null=True, verbose_name='支払いリミット'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='payment_unit_id',
            field=models.IntegerField(null=True, verbose_name='支払い単位ID'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='rank',
            field=models.IntegerField(null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='paymentresult',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='金額'),
        ),
    ]
