# Generated by Django 2.0.3 on 2019-05-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplan',
            name='payment_category_id',
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='payment_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.PaymentCategory', verbose_name='支払いカテゴリID'),
        ),
        migrations.AlterField(
            model_name='paymentresult',
            name='payment_date',
            field=models.DateTimeField(verbose_name='支払日'),
        ),
    ]
