# Generated by Django 2.0.3 on 2019-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20190407_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rank',
            field=models.IntegerField(null=True, verbose_name='表示順'),
        ),
    ]
