# Generated by Django 2.0.3 on 2019-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20190502_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='del_flg',
            field=models.BooleanField(default=0, verbose_name='削除フラグ'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日'),
        ),
    ]
