# Generated by Django 2.0.3 on 2019-04-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_payment_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_unit_id',
            field=models.IntegerField(null=True, verbose_name='支払い単位ID'),
        ),
    ]
