# Generated by Django 2.0.3 on 2019-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20190421_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='payment_category_id',
            field=models.IntegerField(null=True, verbose_name='支払いカテゴリID'),
        ),
    ]
