# Generated by Django 2.0.3 on 2019-04-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20190421_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='amount_plus_flg',
            field=models.BooleanField(default=0, verbose_name='収支区分'),
        ),
    ]
