# Generated by Django 2.0.3 on 2019-06-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_wallethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentresult',
            name='payment_month',
            field=models.DateTimeField(null=True, verbose_name='支払月'),
        ),
    ]
