# Generated by Django 2.0.3 on 2019-04-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_paymentplan_amount_plus_flg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentresult',
            name='payment_plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.PaymentPlan', verbose_name='予算'),
        ),
    ]
