# Generated by Django 2.0.3 on 2019-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_paymentresult_payment_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_month', models.DateTimeField(unique_for_month=True, verbose_name='決算月')),
                ('settlement_date', models.DateTimeField(verbose_name='決算日')),
                ('family_id', models.IntegerField(null=True, verbose_name='家族ID')),
                ('member_id', models.IntegerField(null=True, verbose_name='メンバーID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('del_flg', models.BooleanField(default=0, verbose_name='削除フラグ')),
            ],
        ),
        migrations.AlterField(
            model_name='paymentresult',
            name='payment_date',
            field=models.DateTimeField(null=True, verbose_name='支払日'),
        ),
    ]
