# Generated by Django 2.0.3 on 2019-04-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20190421_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentresult',
            old_name='payment_plan_id',
            new_name='payment_plan',
        ),
    ]
