# Generated by Django 2.0.3 on 2019-06-14 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_doublepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResultSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_plus_flg', models.BooleanField(default=0, verbose_name='収支区分')),
                ('amount', models.IntegerField(null=True, verbose_name='金額')),
                ('memo', models.CharField(max_length=100, null=True, verbose_name='備考')),
                ('rank', models.IntegerField(null=True, verbose_name='表示順')),
                ('payment_month', models.DateTimeField(null=True, verbose_name='支払月')),
                ('payment_date', models.DateTimeField(null=True, verbose_name='支払日')),
                ('sample_flg', models.BooleanField(default=0, verbose_name='サンプルフラグ')),
                ('family_id', models.IntegerField(null=True, verbose_name='家族ID')),
                ('member_id', models.IntegerField(null=True, verbose_name='メンバーID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('del_flg', models.BooleanField(default=0, verbose_name='削除フラグ')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.PaymentPlan', verbose_name='予算')),
            ],
            options={
                'db_table': 'payment_result_sample',
            },
        ),
    ]
