# Generated by Django 2.0.3 on 2019-06-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_paymentresultsample'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='settlement',
            table='settlement',
        ),
    ]
