# Generated by Django 2.0.3 on 2019-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_auto_20190615_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='charge_yyyymm',
            field=models.IntegerField(null=True, verbose_name='請求月'),
        ),
    ]
