# Generated by Django 2.0.3 on 2019-10-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_paymentplan_charge_yyyymm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplan',
            name='charge_yyyymm',
        ),
    ]
