# Generated by Django 2.0.3 on 2019-10-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_remove_paymentplan_charge_yyyymm'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentresult',
            name='charge_month',
            field=models.DateTimeField(null=True, verbose_name='請求月'),
        ),
    ]
