# Generated by Django 2.0.3 on 2019-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name_en', models.CharField(max_length=20, verbose_name='苗字(英)')),
                ('family_name_jp', models.CharField(max_length=20, verbose_name='苗字(日)')),
                ('boss_id', models.IntegerField(verbose_name='代表者ID')),
                ('disp_flg', models.BooleanField(verbose_name='表示フラグ')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('del_flg', models.BooleanField(verbose_name='削除フラグ')),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=20, verbose_name='ログインID')),
                ('password', models.CharField(max_length=20, verbose_name='パスワード')),
                ('family_id', models.IntegerField(verbose_name='家族ID')),
                ('first_name_en', models.CharField(max_length=20, verbose_name='名前(英)')),
                ('first_name_jp', models.CharField(max_length=20, verbose_name='名前(日)')),
                ('birth_day', models.DateTimeField(verbose_name='誕生日')),
                ('session_id', models.CharField(max_length=50, null=True, verbose_name='セッションID')),
                ('disp_flg', models.BooleanField(verbose_name='表示フラグ')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('del_flg', models.BooleanField(verbose_name='削除フラグ')),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
