# Generated by Django 2.0.3 on 2019-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.IntegerField(verbose_name='家族ID')),
                ('first_name_en', models.CharField(max_length=20, verbose_name='名前(英)')),
                ('first_name_jp', models.CharField(max_length=20, verbose_name='名前(日)')),
                ('birth_day', models.DateTimeField(verbose_name='誕生日')),
                ('disp_flg', models.BooleanField(verbose_name='表示フラグ')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('del_flg', models.BooleanField(verbose_name='削除フラグ')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.AlterField(
            model_name='family',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='family',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
