# Generated by Django 2.0.3 on 2019-03-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190324_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='login_id',
            field=models.CharField(max_length=20, verbose_name='ログインID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=20, verbose_name='パスワード'),
        ),
    ]
