# Generated by Django 2.0.3 on 2019-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190324_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='session_id',
            field=models.CharField(max_length=50, null=True, verbose_name='セッションID'),
        ),
    ]
